import XCTest
@testable import PayPal

final class ProvinceTests: XCTestCase {
    struct Land: Codable {
        let prov: Province
    }
    
    func testCaseRawValues() {
        XCTAssertEqual(Province.ciudadAutónomaDeBuenosAires.rawValue, "CIUDAD AUTÓNOMA DE BUENOS AIRES")
        XCTAssertEqual(Province.buenosAires.rawValue, "BUENOS AIRES")
        XCTAssertEqual(Province.catamarca.rawValue, "CATAMARCA")
        XCTAssertEqual(Province.chaco.rawValue, "CHACO")
        XCTAssertEqual(Province.chubut.rawValue, "CHUBUT")
        XCTAssertEqual(Province.corrientes.rawValue, "CORRIENTES")
        XCTAssertEqual(Province.córdoba.rawValue, "CÓRDOBA")
        XCTAssertEqual(Province.entreRíos.rawValue, "ENTRE RÍOS")
        XCTAssertEqual(Province.formosa.rawValue, "FORMOSA")
        XCTAssertEqual(Province.jujuy.rawValue, "JUJUY")
        XCTAssertEqual(Province.laPampa.rawValue, "LA PAMPA")
        XCTAssertEqual(Province.laRioja.rawValue, "LA RIOJA")
        XCTAssertEqual(Province.mendoza.rawValue, "MENDOZA")
        XCTAssertEqual(Province.misiones.rawValue, "MISIONES")
        XCTAssertEqual(Province.neuquén.rawValue, "NEUQUÉN")
        XCTAssertEqual(Province.ríoNegro.rawValue, "RÍO NEGRO")
        XCTAssertEqual(Province.salta.rawValue, "SALTA")
        XCTAssertEqual(Province.sanJuan.rawValue, "SAN JUAN")
        XCTAssertEqual(Province.sanLuis.rawValue, "SAN LUIS")
        XCTAssertEqual(Province.santaCruz.rawValue, "SANTA CRUZ")
        XCTAssertEqual(Province.santaFe.rawValue, "SANTA FE")
        XCTAssertEqual(Province.santiagoDelEstero.rawValue, "SANTIAGO DEL ESTERO")
        XCTAssertEqual(Province.tierraDelFuego.rawValue, "TIERRA DEL FUEGO")
        XCTAssertEqual(Province.tucumán.rawValue, "TUCUMÁN")
        XCTAssertEqual(Province.ac.rawValue, "AC")
        XCTAssertEqual(Province.al.rawValue, "AL")
        XCTAssertEqual(Province.ap.rawValue, "AP")
        XCTAssertEqual(Province.am.rawValue, "AM")
        XCTAssertEqual(Province.ba.rawValue, "BA")
        XCTAssertEqual(Province.ce.rawValue, "CE")
        XCTAssertEqual(Province.df.rawValue, "DF")
        XCTAssertEqual(Province.es.rawValue, "ES")
        XCTAssertEqual(Province.go.rawValue, "GO")
        XCTAssertEqual(Province.ma.rawValue, "MA")
        XCTAssertEqual(Province.mt.rawValue, "MT")
        XCTAssertEqual(Province.ms.rawValue, "MS")
        XCTAssertEqual(Province.mg.rawValue, "MG")
        XCTAssertEqual(Province.pr.rawValue, "PR")
        XCTAssertEqual(Province.pb.rawValue, "PB")
        XCTAssertEqual(Province.pa.rawValue, "PA")
        XCTAssertEqual(Province.pe.rawValue, "PE")
        XCTAssertEqual(Province.pi.rawValue, "PI")
        XCTAssertEqual(Province.rn.rawValue, "RN")
        XCTAssertEqual(Province.rs.rawValue, "RS")
        XCTAssertEqual(Province.rj.rawValue, "RJ")
        XCTAssertEqual(Province.ro.rawValue, "RO")
        XCTAssertEqual(Province.rr.rawValue, "RR")
        XCTAssertEqual(Province.sc.rawValue, "SC")
        XCTAssertEqual(Province.se.rawValue, "SE")
        XCTAssertEqual(Province.sp.rawValue, "SP")
        XCTAssertEqual(Province.to.rawValue, "TO")
        XCTAssertEqual(Province.ab.rawValue, "AB")
        XCTAssertEqual(Province.bc.rawValue, "BC")
        XCTAssertEqual(Province.mb.rawValue, "MB")
        XCTAssertEqual(Province.nb.rawValue, "NB")
        XCTAssertEqual(Province.nl.rawValue, "NL")
        XCTAssertEqual(Province.nt.rawValue, "NT")
        XCTAssertEqual(Province.ns.rawValue, "NS")
        XCTAssertEqual(Province.nu.rawValue, "NU")
        XCTAssertEqual(Province.on.rawValue, "ON")
        XCTAssertEqual(Province.qc.rawValue, "QC")
        XCTAssertEqual(Province.sk.rawValue, "SK")
        XCTAssertEqual(Province.yt.rawValue, "YT")
        XCTAssertEqual(Province.cnAh.rawValue, "CN-AH")
        XCTAssertEqual(Province.cnBj.rawValue, "CN-BJ")
        XCTAssertEqual(Province.cnCq.rawValue, "CN-CQ")
        XCTAssertEqual(Province.cnFj.rawValue, "CN-FJ")
        XCTAssertEqual(Province.cnGd.rawValue, "CN-GD")
        XCTAssertEqual(Province.cnGs.rawValue, "CN-GS")
        XCTAssertEqual(Province.cnGx.rawValue, "CN-GX")
        XCTAssertEqual(Province.cnGz.rawValue, "CN-GZ")
        XCTAssertEqual(Province.cnHa.rawValue, "CN-HA")
        XCTAssertEqual(Province.cnHb.rawValue, "CN-HB")
        XCTAssertEqual(Province.cnHe.rawValue, "CN-HE")
        XCTAssertEqual(Province.cnHi.rawValue, "CN-HI")
        XCTAssertEqual(Province.cnHk.rawValue, "CN-HK")
        XCTAssertEqual(Province.cnHl.rawValue, "CN-HL")
        XCTAssertEqual(Province.cnHn.rawValue, "CN-HN")
        XCTAssertEqual(Province.cnJl.rawValue, "CN-JL")
        XCTAssertEqual(Province.cnJs.rawValue, "CN-JS")
        XCTAssertEqual(Province.cnJx.rawValue, "CN-JX")
        XCTAssertEqual(Province.cnLn.rawValue, "CN-LN")
        XCTAssertEqual(Province.cnMo.rawValue, "CN-MO")
        XCTAssertEqual(Province.cnNm.rawValue, "CN-NM")
        XCTAssertEqual(Province.cnNx.rawValue, "CN-NX")
        XCTAssertEqual(Province.cnQh.rawValue, "CN-QH")
        XCTAssertEqual(Province.cnSc.rawValue, "CN-SC")
        XCTAssertEqual(Province.cnSd.rawValue, "CN-SD")
        XCTAssertEqual(Province.cnSh.rawValue, "CN-SH")
        XCTAssertEqual(Province.cnSn.rawValue, "CN-SN")
        XCTAssertEqual(Province.cnSx.rawValue, "CN-SX")
        XCTAssertEqual(Province.cnTj.rawValue, "CN-TJ")
        XCTAssertEqual(Province.cnTw.rawValue, "CN-TW")
        XCTAssertEqual(Province.cnXj.rawValue, "CN-XJ")
        XCTAssertEqual(Province.cnXz.rawValue, "CN-XZ")
        XCTAssertEqual(Province.cnYn.rawValue, "CN-YN")
        XCTAssertEqual(Province.cnZj.rawValue, "CN-ZJ")
        XCTAssertEqual(Province.andamanAndNicobarIslands.rawValue, "Andaman and Nicobar Islands")
        XCTAssertEqual(Province.andhraPradesh.rawValue, "Andhra Pradesh")
        XCTAssertEqual(Province.apo.rawValue, "APO")
        XCTAssertEqual(Province.arunachalPradesh.rawValue, "Arunachal Pradesh")
        XCTAssertEqual(Province.assam.rawValue, "Assam")
        XCTAssertEqual(Province.bihar.rawValue, "Bihar")
        XCTAssertEqual(Province.chandigarh.rawValue, "Chandigarh")
        XCTAssertEqual(Province.chhattisgarh.rawValue, "Chhattisgarh")
        XCTAssertEqual(Province.dadraAndNagarHaveli.rawValue, "Dadra and Nagar Haveli")
        XCTAssertEqual(Province.damanAndDiu.rawValue, "Daman and Diu")
        XCTAssertEqual(Province.delhiNCT.rawValue, "Delhi (NCT)")
        XCTAssertEqual(Province.goa.rawValue, "Goa")
        XCTAssertEqual(Province.gujarat.rawValue, "Gujarat")
        XCTAssertEqual(Province.haryana.rawValue, "Haryana")
        XCTAssertEqual(Province.himachalPradesh.rawValue, "Himachal Pradesh")
        XCTAssertEqual(Province.jammuAndKashmir.rawValue, "Jammu and Kashmir")
        XCTAssertEqual(Province.jharkhand.rawValue, "Jharkhand")
        XCTAssertEqual(Province.karnataka.rawValue, "Karnataka")
        XCTAssertEqual(Province.kerala.rawValue, "Kerala")
        XCTAssertEqual(Province.lakshadweep.rawValue, "Lakshadweep")
        XCTAssertEqual(Province.madhyaPradesh.rawValue, "Madhya Pradesh")
        XCTAssertEqual(Province.maharashtra.rawValue, "Maharashtra")
        XCTAssertEqual(Province.manipur.rawValue, "Manipur")
        XCTAssertEqual(Province.meghalaya.rawValue, "Meghalaya")
        XCTAssertEqual(Province.mizoram.rawValue, "Mizoram")
        XCTAssertEqual(Province.nagaland.rawValue, "Nagaland")
        XCTAssertEqual(Province.odisha.rawValue, "Odisha")
        XCTAssertEqual(Province.puducherry.rawValue, "Puducherry")
        XCTAssertEqual(Province.punjab.rawValue, "Punjab")
        XCTAssertEqual(Province.rajasthan.rawValue, "Rajasthan")
        XCTAssertEqual(Province.sikkim.rawValue, "Sikkim")
        XCTAssertEqual(Province.tamilNadu.rawValue, "Tamil Nadu")
        XCTAssertEqual(Province.telangana.rawValue, "Telangana")
        XCTAssertEqual(Province.tripura.rawValue, "Tripura")
        XCTAssertEqual(Province.uttarPradesh.rawValue, "Uttar Pradesh")
        XCTAssertEqual(Province.uttarakhand.rawValue, "Uttarakhand")
        XCTAssertEqual(Province.westBengal.rawValue, "West Bengal")
        XCTAssertEqual(Province.idBa.rawValue, "ID-BA")
        XCTAssertEqual(Province.idBb.rawValue, "ID-BB")
        XCTAssertEqual(Province.idBt.rawValue, "ID-BT")
        XCTAssertEqual(Province.idBe.rawValue, "ID-BE")
        XCTAssertEqual(Province.idYo.rawValue, "ID-YO")
        XCTAssertEqual(Province.idJk.rawValue, "ID-JK")
        XCTAssertEqual(Province.idGo.rawValue, "ID-GO")
        XCTAssertEqual(Province.idJa.rawValue, "ID-JA")
        XCTAssertEqual(Province.idJb.rawValue, "ID-JB")
        XCTAssertEqual(Province.idJt.rawValue, "ID-JT")
        XCTAssertEqual(Province.idJi.rawValue, "ID-JI")
        XCTAssertEqual(Province.idKb.rawValue, "ID-KB")
        XCTAssertEqual(Province.idKs.rawValue, "ID-KS")
        XCTAssertEqual(Province.idKt.rawValue, "ID-KT")
        XCTAssertEqual(Province.idKi.rawValue, "ID-KI")
        XCTAssertEqual(Province.idKu.rawValue, "ID-KU")
        XCTAssertEqual(Province.idKr.rawValue, "ID-KR")
        XCTAssertEqual(Province.idLa.rawValue, "ID-LA")
        XCTAssertEqual(Province.idMa.rawValue, "ID-MA")
        XCTAssertEqual(Province.idMu.rawValue, "ID-MU")
        XCTAssertEqual(Province.idAc.rawValue, "ID-AC")
        XCTAssertEqual(Province.idNb.rawValue, "ID-NB")
        XCTAssertEqual(Province.idNt.rawValue, "ID-NT")
        XCTAssertEqual(Province.idPa.rawValue, "ID-PA")
        XCTAssertEqual(Province.idPb.rawValue, "ID-PB")
        XCTAssertEqual(Province.idRi.rawValue, "ID-RI")
        XCTAssertEqual(Province.idSr.rawValue, "ID-SR")
        XCTAssertEqual(Province.idSn.rawValue, "ID-SN")
        XCTAssertEqual(Province.idSt.rawValue, "ID-ST")
        XCTAssertEqual(Province.idSg.rawValue, "ID-SG")
        XCTAssertEqual(Province.idSa.rawValue, "ID-SA")
        XCTAssertEqual(Province.idSb.rawValue, "ID-SB")
        XCTAssertEqual(Province.idSs.rawValue, "ID-SS")
        XCTAssertEqual(Province.idSu.rawValue, "ID-SU")
        XCTAssertEqual(Province.ag.rawValue, "AG")
        XCTAssertEqual(Province.an.rawValue, "AN")
        XCTAssertEqual(Province.ao.rawValue, "AO")
        XCTAssertEqual(Province.ar.rawValue, "AR")
        XCTAssertEqual(Province.at.rawValue, "AT")
        XCTAssertEqual(Province.av.rawValue, "AV")
        XCTAssertEqual(Province.bt.rawValue, "BT")
        XCTAssertEqual(Province.bl.rawValue, "BL")
        XCTAssertEqual(Province.bn.rawValue, "BN")
        XCTAssertEqual(Province.bg.rawValue, "BG")
        XCTAssertEqual(Province.bi.rawValue, "BI")
        XCTAssertEqual(Province.bo.rawValue, "BO")
        XCTAssertEqual(Province.bz.rawValue, "BZ")
        XCTAssertEqual(Province.bs.rawValue, "BS")
        XCTAssertEqual(Province.br.rawValue, "BR")
        XCTAssertEqual(Province.ca.rawValue, "CA")
        XCTAssertEqual(Province.cl.rawValue, "CL")
        XCTAssertEqual(Province.cb.rawValue, "CB")
        XCTAssertEqual(Province.ci.rawValue, "CI")
        XCTAssertEqual(Province.ct.rawValue, "CT")
        XCTAssertEqual(Province.cz.rawValue, "CZ")
        XCTAssertEqual(Province.ch.rawValue, "CH")
        XCTAssertEqual(Province.co.rawValue, "CO")
        XCTAssertEqual(Province.cs.rawValue, "CS")
        XCTAssertEqual(Province.cr.rawValue, "CR")
        XCTAssertEqual(Province.kr.rawValue, "KR")
        XCTAssertEqual(Province.en.rawValue, "EN")
        XCTAssertEqual(Province.fm.rawValue, "FM")
        XCTAssertEqual(Province.fe.rawValue, "FE")
        XCTAssertEqual(Province.fi.rawValue, "FI")
        XCTAssertEqual(Province.fg.rawValue, "FG")
        XCTAssertEqual(Province.fc.rawValue, "FC")
        XCTAssertEqual(Province.fr.rawValue, "FR")
        XCTAssertEqual(Province.ge.rawValue, "GE")
        XCTAssertEqual(Province.gr.rawValue, "GR")
        XCTAssertEqual(Province.im.rawValue, "IM")
        XCTAssertEqual(Province.`is`.rawValue, "IS")
        XCTAssertEqual(Province.aq.rawValue, "AQ")
        XCTAssertEqual(Province.lt.rawValue, "LT")
        XCTAssertEqual(Province.le.rawValue, "LE")
        XCTAssertEqual(Province.lc.rawValue, "LC")
        XCTAssertEqual(Province.li.rawValue, "LI")
        XCTAssertEqual(Province.lo.rawValue, "LO")
        XCTAssertEqual(Province.lu.rawValue, "LU")
        XCTAssertEqual(Province.mc.rawValue, "MC")
        XCTAssertEqual(Province.mn.rawValue, "MN")
        XCTAssertEqual(Province.vs.rawValue, "VS")
        XCTAssertEqual(Province.me.rawValue, "ME")
        XCTAssertEqual(Province.mi.rawValue, "MI")
        XCTAssertEqual(Province.mo.rawValue, "MO")
        XCTAssertEqual(Province.na.rawValue, "NA")
        XCTAssertEqual(Province.no.rawValue, "NO")
        XCTAssertEqual(Province.og.rawValue, "OG")
        XCTAssertEqual(Province.ot.rawValue, "OT")
        XCTAssertEqual(Province.or.rawValue, "OR")
        XCTAssertEqual(Province.pd.rawValue, "PD")
        XCTAssertEqual(Province.pv.rawValue, "PV")
        XCTAssertEqual(Province.pg.rawValue, "PG")
        XCTAssertEqual(Province.pu.rawValue, "PU")
        XCTAssertEqual(Province.pc.rawValue, "PC")
        XCTAssertEqual(Province.pt.rawValue, "PT")
        XCTAssertEqual(Province.pn.rawValue, "PN")
        XCTAssertEqual(Province.pz.rawValue, "PZ")
        XCTAssertEqual(Province.po.rawValue, "PO")
        XCTAssertEqual(Province.rg.rawValue, "RG")
        XCTAssertEqual(Province.ra.rawValue, "RA")
        XCTAssertEqual(Province.rc.rawValue, "RC")
        XCTAssertEqual(Province.re.rawValue, "RE")
        XCTAssertEqual(Province.ri.rawValue, "RI")
        XCTAssertEqual(Province.rm.rawValue, "RM")
        XCTAssertEqual(Province.sa.rawValue, "SA")
        XCTAssertEqual(Province.ss.rawValue, "SS")
        XCTAssertEqual(Province.sv.rawValue, "SV")
        XCTAssertEqual(Province.si.rawValue, "SI")
        XCTAssertEqual(Province.sr.rawValue, "SR")
        XCTAssertEqual(Province.so.rawValue, "SO")
        XCTAssertEqual(Province.ta.rawValue, "TA")
        XCTAssertEqual(Province.te.rawValue, "TE")
        XCTAssertEqual(Province.tr.rawValue, "TR")
        XCTAssertEqual(Province.tp.rawValue, "TP")
        XCTAssertEqual(Province.tn.rawValue, "TN")
        XCTAssertEqual(Province.tv.rawValue, "TV")
        XCTAssertEqual(Province.ts.rawValue, "TS")
        XCTAssertEqual(Province.ud.rawValue, "UD")
        XCTAssertEqual(Province.va.rawValue, "VA")
        XCTAssertEqual(Province.ve.rawValue, "VE")
        XCTAssertEqual(Province.vb.rawValue, "VB")
        XCTAssertEqual(Province.vc.rawValue, "VC")
        XCTAssertEqual(Province.vr.rawValue, "VR")
        XCTAssertEqual(Province.vv.rawValue, "VV")
        XCTAssertEqual(Province.vi.rawValue, "VI")
        XCTAssertEqual(Province.vt.rawValue, "VT")
        XCTAssertEqual(Province.aichiKen.rawValue, "AICHI-KEN")
        XCTAssertEqual(Province.akitaKen.rawValue, "AKITA-KEN")
        XCTAssertEqual(Province.aomoriKen.rawValue, "AOMORI-KEN")
        XCTAssertEqual(Province.chibaKen.rawValue, "CHIBA-KEN")
        XCTAssertEqual(Province.ehimeKen.rawValue, "EHIME-KEN")
        XCTAssertEqual(Province.fukuiKen.rawValue, "FUKUI-KEN")
        XCTAssertEqual(Province.fukuokaKen.rawValue, "FUKUOKA-KEN")
        XCTAssertEqual(Province.fukushimaKen.rawValue, "FUKUSHIMA-KEN")
        XCTAssertEqual(Province.gifuKen.rawValue, "GIFU-KEN")
        XCTAssertEqual(Province.gunmaKen.rawValue, "GUNMA-KEN")
        XCTAssertEqual(Province.hiroshimaKen.rawValue, "HIROSHIMA-KEN")
        XCTAssertEqual(Province.hokkaido.rawValue, "HOKKAIDO")
        XCTAssertEqual(Province.hyogoKen.rawValue, "HYOGO-KEN")
        XCTAssertEqual(Province.ibarakiKen.rawValue, "IBARAKI-KEN")
        XCTAssertEqual(Province.ishikawaKen.rawValue, "ISHIKAWA-KEN")
        XCTAssertEqual(Province.iwateKen.rawValue, "IWATE-KEN")
        XCTAssertEqual(Province.kagawaKen.rawValue, "KAGAWA-KEN")
        XCTAssertEqual(Province.kagoshimaKen.rawValue, "KAGOSHIMA-KEN")
        XCTAssertEqual(Province.kanagawaKen.rawValue, "KANAGAWA-KEN")
        XCTAssertEqual(Province.kochiKen.rawValue, "KOCHI-KEN")
        XCTAssertEqual(Province.kumamotoKen.rawValue, "KUMAMOTO-KEN")
        XCTAssertEqual(Province.kyotoFu.rawValue, "KYOTO-FU")
        XCTAssertEqual(Province.mieKen.rawValue, "MIE-KEN")
        XCTAssertEqual(Province.miyagiKen.rawValue, "MIYAGI-KEN")
        XCTAssertEqual(Province.miyazakiKen.rawValue, "MIYAZAKI-KEN")
        XCTAssertEqual(Province.naganoKen.rawValue, "NAGANO-KEN")
        XCTAssertEqual(Province.nagasakiKen.rawValue, "NAGASAKI-KEN")
        XCTAssertEqual(Province.naraKen.rawValue, "NARA-KEN")
        XCTAssertEqual(Province.niigataKen.rawValue, "NIIGATA-KEN")
        XCTAssertEqual(Province.oitaKen.rawValue, "OITA-KEN")
        XCTAssertEqual(Province.okayamaKen.rawValue, "OKAYAMA-KEN")
        XCTAssertEqual(Province.okinawaKen.rawValue, "OKINAWA-KEN")
        XCTAssertEqual(Province.osakaFu.rawValue, "OSAKA-FU")
        XCTAssertEqual(Province.sagaKen.rawValue, "SAGA-KEN")
        XCTAssertEqual(Province.saitamaKen.rawValue, "SAITAMA-KEN")
        XCTAssertEqual(Province.shigaKen.rawValue, "SHIGA-KEN")
        XCTAssertEqual(Province.shimaneKen.rawValue, "SHIMANE-KEN")
        XCTAssertEqual(Province.shizuokaKen.rawValue, "SHIZUOKA-KEN")
        XCTAssertEqual(Province.tochigiKen.rawValue, "TOCHIGI-KEN")
        XCTAssertEqual(Province.tokushimaKen.rawValue, "TOKUSHIMA-KEN")
        XCTAssertEqual(Province.tokyoTo.rawValue, "TOKYO-TO")
        XCTAssertEqual(Province.tottoriKen.rawValue, "TOTTORI-KEN")
        XCTAssertEqual(Province.toyamaKen.rawValue, "TOYAMA-KEN")
        XCTAssertEqual(Province.wakayamaKen.rawValue, "WAKAYAMA-KEN")
        XCTAssertEqual(Province.yamagataKen.rawValue, "YAMAGATA-KEN")
        XCTAssertEqual(Province.yamaguchiKen.rawValue, "YAMAGUCHI-KEN")
        XCTAssertEqual(Province.yamanashiKen.rawValue, "YAMANASHI-KEN")
        XCTAssertEqual(Province.ags.rawValue, "AGS")
        XCTAssertEqual(Province.bcs.rawValue, "BCS")
        XCTAssertEqual(Province.camp.rawValue, "CAMP")
        XCTAssertEqual(Province.chis.rawValue, "CHIS")
        XCTAssertEqual(Province.chih.rawValue, "CHIH")
        XCTAssertEqual(Province.cdmx.rawValue, "CDMX")
        XCTAssertEqual(Province.coah.rawValue, "COAH")
        XCTAssertEqual(Province.col.rawValue, "COL")
        XCTAssertEqual(Province.dgo.rawValue, "DGO")
        XCTAssertEqual(Province.mex.rawValue, "MEX")
        XCTAssertEqual(Province.gto.rawValue, "GTO")
        XCTAssertEqual(Province.gro.rawValue, "GRO")
        XCTAssertEqual(Province.hgo.rawValue, "HGO")
        XCTAssertEqual(Province.jal.rawValue, "JAL")
        XCTAssertEqual(Province.mich.rawValue, "MICH")
        XCTAssertEqual(Province.mor.rawValue, "MOR")
        XCTAssertEqual(Province.nay.rawValue, "NAY")
        XCTAssertEqual(Province.oax.rawValue, "OAX")
        XCTAssertEqual(Province.pue.rawValue, "PUE")
        XCTAssertEqual(Province.qro.rawValue, "QRO")
        XCTAssertEqual(Province.qROO.rawValue, "Q ROO")
        XCTAssertEqual(Province.slp.rawValue, "SLP")
        XCTAssertEqual(Province.sin.rawValue, "SIN")
        XCTAssertEqual(Province.son.rawValue, "SON")
        XCTAssertEqual(Province.tab.rawValue, "TAB")
        XCTAssertEqual(Province.tamps.rawValue, "TAMPS")
        XCTAssertEqual(Province.tlax.rawValue, "TLAX")
        XCTAssertEqual(Province.ver.rawValue, "VER")
        XCTAssertEqual(Province.yuc.rawValue, "YUC")
        XCTAssertEqual(Province.zac.rawValue, "ZAC")
        XCTAssertEqual(Province.amnatCharoen.rawValue, "Amnat Charoen")
        XCTAssertEqual(Province.angThong.rawValue, "Ang Thong")
        XCTAssertEqual(Province.bangkok.rawValue, "Bangkok")
        XCTAssertEqual(Province.buengKan.rawValue, "Bueng Kan")
        XCTAssertEqual(Province.buriRam.rawValue, "Buri Ram")
        XCTAssertEqual(Province.chachoengsao.rawValue, "Chachoengsao")
        XCTAssertEqual(Province.chaiNat.rawValue, "Chai Nat")
        XCTAssertEqual(Province.chaiyaphum.rawValue, "Chaiyaphum")
        XCTAssertEqual(Province.chanthaburi.rawValue, "Chanthaburi")
        XCTAssertEqual(Province.chiangMai.rawValue, "Chiang Mai")
        XCTAssertEqual(Province.chiangRai.rawValue, "Chiang Rai")
        XCTAssertEqual(Province.chonBuri.rawValue, "Chon Buri")
        XCTAssertEqual(Province.chumphon.rawValue, "Chumphon")
        XCTAssertEqual(Province.kalasin.rawValue, "Kalasin")
        XCTAssertEqual(Province.kamphaengPhet.rawValue, "Kamphaeng Phet")
        XCTAssertEqual(Province.kanchanaburi.rawValue, "Kanchanaburi")
        XCTAssertEqual(Province.khonKaen.rawValue, "Khon Kaen")
        XCTAssertEqual(Province.krabi.rawValue, "Krabi")
        XCTAssertEqual(Province.lampang.rawValue, "Lampang")
        XCTAssertEqual(Province.lamphun.rawValue, "Lamphun")
        XCTAssertEqual(Province.loei.rawValue, "Loei")
        XCTAssertEqual(Province.lopBuri.rawValue, "Lop Buri")
        XCTAssertEqual(Province.maeHongSon.rawValue, "Mae Hong Son")
        XCTAssertEqual(Province.mahaSarakham.rawValue, "Maha Sarakham")
        XCTAssertEqual(Province.mukdahan.rawValue, "Mukdahan")
        XCTAssertEqual(Province.nakhonNayok.rawValue, "Nakhon Nayok")
        XCTAssertEqual(Province.nakhonPathom.rawValue, "Nakhon Pathom")
        XCTAssertEqual(Province.nakhonPhanom.rawValue, "Nakhon Phanom")
        XCTAssertEqual(Province.nakhonRatchasima.rawValue, "Nakhon Ratchasima")
        XCTAssertEqual(Province.nakhonSawan.rawValue, "Nakhon Sawan")
        XCTAssertEqual(Province.nakhonSiThammarat.rawValue, "Nakhon Si Thammarat")
        XCTAssertEqual(Province.nan.rawValue, "Nan")
        XCTAssertEqual(Province.narathiwat.rawValue, "Narathiwat")
        XCTAssertEqual(Province.nongBuaLamphu.rawValue, "Nong Bua Lamphu")
        XCTAssertEqual(Province.nongKhai.rawValue, "Nong Khai")
        XCTAssertEqual(Province.nonthaburi.rawValue, "Nonthaburi")
        XCTAssertEqual(Province.pathumThani.rawValue, "Pathum Thani")
        XCTAssertEqual(Province.pattani.rawValue, "Pattani")
        XCTAssertEqual(Province.phangNga.rawValue, "Phang Nga")
        XCTAssertEqual(Province.phatthalung.rawValue, "Phatthalung")
        XCTAssertEqual(Province.phatthaya.rawValue, "Phatthaya")
        XCTAssertEqual(Province.phayao.rawValue, "Phayao")
        XCTAssertEqual(Province.phetchabun.rawValue, "Phetchabun")
        XCTAssertEqual(Province.phetchaburi.rawValue, "Phetchaburi")
        XCTAssertEqual(Province.phichit.rawValue, "Phichit")
        XCTAssertEqual(Province.phitsanulok.rawValue, "Phitsanulok")
        XCTAssertEqual(Province.phraNakhonSiAyutthaya.rawValue, "Phra Nakhon Si Ayutthaya")
        XCTAssertEqual(Province.phrae.rawValue, "Phrae")
        XCTAssertEqual(Province.phuket.rawValue, "Phuket")
        XCTAssertEqual(Province.prachinBuri.rawValue, "Prachin Buri")
        XCTAssertEqual(Province.prachuapKhiriKhan.rawValue, "Prachuap Khiri Khan")
        XCTAssertEqual(Province.ranong.rawValue, "Ranong")
        XCTAssertEqual(Province.ratchaburi.rawValue, "Ratchaburi")
        XCTAssertEqual(Province.rayong.rawValue, "Rayong")
        XCTAssertEqual(Province.roiEt.rawValue, "Roi Et")
        XCTAssertEqual(Province.saKaeo.rawValue, "Sa Kaeo")
        XCTAssertEqual(Province.sakonNakhon.rawValue, "Sakon Nakhon")
        XCTAssertEqual(Province.samutPrakan.rawValue, "Samut Prakan")
        XCTAssertEqual(Province.samutSakhon.rawValue, "Samut Sakhon")
        XCTAssertEqual(Province.samutSongkhram.rawValue, "Samut Songkhram")
        XCTAssertEqual(Province.saraburi.rawValue, "Saraburi")
        XCTAssertEqual(Province.satun.rawValue, "Satun")
        XCTAssertEqual(Province.siSaKet.rawValue, "Si Sa Ket")
        XCTAssertEqual(Province.singBuri.rawValue, "Sing Buri")
        XCTAssertEqual(Province.songkhla.rawValue, "Songkhla")
        XCTAssertEqual(Province.sukhothai.rawValue, "Sukhothai")
        XCTAssertEqual(Province.suphanBuri.rawValue, "Suphan Buri")
        XCTAssertEqual(Province.suratThani.rawValue, "Surat Thani")
        XCTAssertEqual(Province.surin.rawValue, "Surin")
        XCTAssertEqual(Province.tak.rawValue, "Tak")
        XCTAssertEqual(Province.trang.rawValue, "Trang")
        XCTAssertEqual(Province.trat.rawValue, "Trat")
        XCTAssertEqual(Province.ubonRatchathani.rawValue, "Ubon Ratchathani")
        XCTAssertEqual(Province.udonThani.rawValue, "Udon Thani")
        XCTAssertEqual(Province.uthaiThani.rawValue, "Uthai Thani")
        XCTAssertEqual(Province.uttaradit.rawValue, "Uttaradit")
        XCTAssertEqual(Province.yala.rawValue, "Yala")
        XCTAssertEqual(Province.yasothon.rawValue, "Yasothon")
        XCTAssertEqual(Province.ak.rawValue, "AK")
        XCTAssertEqual(Province.az.rawValue, "AZ")
        XCTAssertEqual(Province.de.rawValue, "DE")
        XCTAssertEqual(Province.dc.rawValue, "DC")
        XCTAssertEqual(Province.fl.rawValue, "FL")
        XCTAssertEqual(Province.ga.rawValue, "GA")
        XCTAssertEqual(Province.hi.rawValue, "HI")
        XCTAssertEqual(Province.il.rawValue, "IL")
        XCTAssertEqual(Province.`in`.rawValue, "IN")
        XCTAssertEqual(Province.ia.rawValue, "IA")
        XCTAssertEqual(Province.ks.rawValue, "KS")
        XCTAssertEqual(Province.ky.rawValue, "KY")
        XCTAssertEqual(Province.la.rawValue, "LA")
        XCTAssertEqual(Province.md.rawValue, "MD")
        XCTAssertEqual(Province.ne.rawValue, "NE")
        XCTAssertEqual(Province.nv.rawValue, "NV")
        XCTAssertEqual(Province.nh.rawValue, "NH")
        XCTAssertEqual(Province.nj.rawValue, "NJ")
        XCTAssertEqual(Province.nm.rawValue, "NM")
        XCTAssertEqual(Province.ny.rawValue, "NY")
        XCTAssertEqual(Province.nc.rawValue, "NC")
        XCTAssertEqual(Province.nd.rawValue, "ND")
        XCTAssertEqual(Province.oh.rawValue, "OH")
        XCTAssertEqual(Province.ok.rawValue, "OK")
        XCTAssertEqual(Province.sd.rawValue, "SD")
        XCTAssertEqual(Province.tx.rawValue, "TX")
        XCTAssertEqual(Province.ut.rawValue, "UT")
        XCTAssertEqual(Province.wa.rawValue, "WA")
        XCTAssertEqual(Province.wv.rawValue, "WV")
        XCTAssertEqual(Province.wi.rawValue, "WI")
        XCTAssertEqual(Province.wy.rawValue, "WY")
        XCTAssertEqual(Province.aa.rawValue, "AA")
        XCTAssertEqual(Province.ae.rawValue, "AE")
        XCTAssertEqual(Province.`as`.rawValue, "AS")
        XCTAssertEqual(Province.gu.rawValue, "GU")
        XCTAssertEqual(Province.mh.rawValue, "MH")
        XCTAssertEqual(Province.mp.rawValue, "MP")
        XCTAssertEqual(Province.pw.rawValue, "PW")
    }
    
    func testAllCase() {
        XCTAssertEqual(Province.allCases.count, 453)
        XCTAssertEqual(Province.allCases, [
            .ciudadAutónomaDeBuenosAires, .buenosAires, .catamarca, .chaco, .chubut, .corrientes, .córdoba, .entreRíos, .formosa, .jujuy, .laPampa,
            .laRioja, .mendoza, .misiones, .neuquén, .ríoNegro, .salta, .sanJuan, .sanLuis, .santaCruz, .santaFe, .santiagoDelEstero,
            .tierraDelFuego, .tucumán, .ac, .al, .ap, .am, .ba, .ce, .df, .es, .go, .ma, .mt, .ms, .mg, .pr, .pb, .pa, .pe, .pi, .rn, .rs, .rj, .ro,
            .rr, .sc, .se, .sp, .to, .ab, .bc, .mb, .nb, .nl, .nt, .ns, .nu, .on, .qc, .sk, .yt, .cnAh, .cnBj, .cnCq, .cnFj, .cnGd, .cnGs, .cnGx,
            .cnGz, .cnHa, .cnHb, .cnHe, .cnHi, .cnHk, .cnHl, .cnHn, .cnJl, .cnJs, .cnJx, .cnLn, .cnMo, .cnNm, .cnNx, .cnQh, .cnSc, .cnSd, .cnSh,
            .cnSn, .cnSx, .cnTj, .cnTw, .cnXj, .cnXz, .cnYn, .cnZj, .andamanAndNicobarIslands, .andhraPradesh, .apo, .arunachalPradesh, .assam,
            .bihar, .chandigarh, .chhattisgarh, .dadraAndNagarHaveli, .damanAndDiu, .delhiNCT, .goa, .gujarat, .haryana, .himachalPradesh,
            .jammuAndKashmir, .jharkhand, .karnataka, .kerala, .lakshadweep, .madhyaPradesh, .maharashtra, .manipur, .meghalaya, .mizoram,
            .nagaland, .odisha, .puducherry, .punjab, .rajasthan, .sikkim, .tamilNadu, .telangana, .tripura, .uttarPradesh, .uttarakhand,
            .westBengal, .idBa, .idBb, .idBt, .idBe, .idYo, .idJk, .idGo, .idJa, .idJb, .idJt, .idJi, .idKb, .idKs, .idKt, .idKi, .idKu, .idKr,
            .idLa, .idMa, .idMu, .idAc, .idNb, .idNt, .idPa, .idPb, .idRi, .idSr, .idSn, .idSt, .idSg, .idSa, .idSb, .idSs, .idSu, .ag, .an, .ao,
            .ar, .at, .av, .bt, .bl, .bn, .bg, .bi, .bo, .bz, .bs, .br, .ca, .cl, .cb, .ci, .ct, .cz, .ch, .co, .cs, .cr, .kr, .en, .fm, .fe, .fi,
            .fg, .fc, .fr, .ge, .gr, .im, .`is`, .aq, .lt, .le, .lc, .li, .lo, .lu, .mc, .mn, .vs, .me, .mi, .mo, .na, .no, .og, .ot, .or, .pd,
            .pv, .pg, .pu, .pc, .pt, .pn, .pz, .po, .rg, .ra, .rc, .re, .ri, .rm, .sa, .ss, .sv, .si, .sr, .so, .ta, .te, .tr, .tp, .tn, .tv, .ts,
            .ud, .va, .ve, .vb, .vc, .vr, .vv, .vi, .vt, .aichiKen, .akitaKen, .aomoriKen, .chibaKen, .ehimeKen, .fukuiKen, .fukuokaKen,
            .fukushimaKen, .gifuKen, .gunmaKen, .hiroshimaKen, .hokkaido, .hyogoKen, .ibarakiKen, .ishikawaKen, .iwateKen, .kagawaKen,
            .kagoshimaKen, .kanagawaKen, .kochiKen, .kumamotoKen, .kyotoFu, .mieKen, .miyagiKen, .miyazakiKen, .naganoKen, .nagasakiKen, .naraKen,
            .niigataKen, .oitaKen, .okayamaKen, .okinawaKen, .osakaFu, .sagaKen, .saitamaKen, .shigaKen, .shimaneKen, .shizuokaKen, .tochigiKen,
            .tokushimaKen, .tokyoTo, .tottoriKen, .toyamaKen, .wakayamaKen, .yamagataKen, .yamaguchiKen, .yamanashiKen, .ags, .bcs, .camp, .chis,
            .chih, .cdmx, .coah, .col, .dgo, .mex, .gto, .gro, .hgo, .jal, .mich, .mor, .nay, .oax, .pue, .qro, .qROO, .slp, .sin, .son, .tab,
            .tamps, .tlax, .ver, .yuc, .zac, .amnatCharoen, .angThong, .bangkok, .buengKan, .buriRam, .chachoengsao, .chaiNat, .chaiyaphum,
            .chanthaburi, .chiangMai, .chiangRai, .chonBuri, .chumphon, .kalasin, .kamphaengPhet, .kanchanaburi, .khonKaen, .krabi, .lampang,
            .lamphun, .loei, .lopBuri, .maeHongSon, .mahaSarakham, .mukdahan, .nakhonNayok, .nakhonPathom, .nakhonPhanom, .nakhonRatchasima,
            .nakhonSawan, .nakhonSiThammarat, .nan, .narathiwat, .nongBuaLamphu, .nongKhai, .nonthaburi, .pathumThani, .pattani, .phangNga,
            .phatthalung, .phatthaya, .phayao, .phetchabun, .phetchaburi, .phichit, .phitsanulok, .phraNakhonSiAyutthaya, .phrae, .phuket,
            .prachinBuri, .prachuapKhiriKhan, .ranong, .ratchaburi, .rayong, .roiEt, .saKaeo, .sakonNakhon, .samutPrakan, .samutSakhon,
            .samutSongkhram, .saraburi, .satun, .siSaKet, .singBuri, .songkhla, .sukhothai, .suphanBuri, .suratThani, .surin, .tak, .trang, .trat,
            .ubonRatchathani, .udonThani, .uthaiThani, .uttaradit, .yala, .yasothon, .ak, .az, .de, .dc, .fl, .ga, .hi, .il, .`in`, .ia, .ks, .ky,
            .la, .md, .ne, .nv, .nh, .nj, .nm, .ny, .nc, .nd, .oh, .ok, .sd, .tx, .ut, .wa, .wv, .wi, .wy, .aa, .ae, .`as`, .gu, .mh, .mp, .pw
        ])
    }
    
    func testEncoding()throws {
        let encoder = JSONEncoder()
        let ciudadAutónomaDeBuenosAires = try String(data: encoder.encode(Land(prov: .ciudadAutónomaDeBuenosAires)), encoding: .utf8)
        let mp = try String(data: encoder.encode(Land(prov: .mp)), encoding: .utf8)

        XCTAssertEqual(ciudadAutónomaDeBuenosAires, "{\"prov\":\"CIUDAD AUTÓNOMA DE BUENOS AIRES\"}")
        XCTAssertEqual(mp, "{\"prov\":\"MP\"}")
    }
    
    func testDecoding()throws {
        let decoder = JSONDecoder()
        let gifuKen = """
        {
            "prov": "GIFU-KEN"
        }
        """.data(using: .utf8)!
        let cnXj = """
        {
            "prov": "CN-XJ"
        }
        """

        try XCTAssertEqual(decoder.decode(Land.self, from: gifuKen).prov, .gifuKen)
        try XCTAssertEqual(decoder.decode(Land.self, from: cnXj).prov, .cnXj)
    }
    
    static var allTests: [(String, (ProvinceTests) -> ()throws -> ())] = [
        ("testCaseRawValues", testCaseRawValues),
        ("testAllCase", testAllCase),
        ("testEncoding", testEncoding),
        ("testDecoding", testDecoding)
    ]
}




